baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'My New Hugo Site'
theme = 'hugo-theme-stack'
[params]
  mainSections = ['posts']  # ğŸ‘ˆ å…³é”®ï¼šå‘Šè¯‰ä¸»é¢˜å»å“ªæ‰¾æ–‡ç« 
  
  [params.sidebar]
    emoji = 'ğŸ¥'
  
  [params.footer]
    since = 2026